"""Server configuration.

Environment variables:
- ``PT_DATA_DIR``    data directory (default ``<server dir>/data``)
- ``PT_JWT_SECRET``  stable JWT signing secret (default: generated once and
  persisted to ``<data_dir>/jwt_secret`` so restarts don't log everyone out)
- ``PT_STATIC_DIR``  frontend build output to serve (default ``<repo>/dist``)
- ``PT_HOST`` / ``PT_PORT``  bind address for ``python main.py`` (127.0.0.1:8000)

OneTap integration mode (mutually exclusive with the standalone mode above):
- ``PT_ONETAP_INTEGRATION``  ``1`` = integration mode, ``0``/unset = standalone.
  Any other value is a startup error: the two modes must be chosen explicitly,
  never guessed (no implicit mixing of /api/* and /int/v1 routes).
- ``PT_ONETAP_SERVICE_KEY``  shared secret with the OneTap game gateway;
  required (>= 32 chars) in integration mode — startup fails otherwise.
- ``PT_ONETAP_DB``  integration database path (default
  ``<data_dir>/phitogether-onetap.db``, kept apart from the standalone
  ``phitogether.db`` so module accounts never touch standalone data).
"""
import logging
import os
import secrets
import sys
import tempfile
from pathlib import Path

_log = logging.getLogger(__name__)


def server_root() -> Path:
    return Path(__file__).resolve().parent


def _default_data_dir() -> str:
    if getattr(sys, "frozen", False):
        return str(Path(sys.executable).parent / "data")
    return str(server_root() / "data")


def _chmod_600(path: str) -> None:
    """Best effort: keep the secret file owner-only (no-op on Windows)."""
    try:
        os.chmod(path, 0o600)
    except (OSError, NotImplementedError):
        pass


def _resolve_jwt_secret(data_dir: str) -> str:
    env_secret = os.environ.get("PT_JWT_SECRET")
    if env_secret:
        return env_secret

    secret_path = Path(data_dir) / "jwt_secret"
    try:
        existing = secret_path.read_text(encoding="utf-8").strip()
        if existing:
            return existing
    except (OSError, ValueError):
        pass

    new_secret = secrets.token_urlsafe(48)
    try:
        Path(data_dir).mkdir(parents=True, exist_ok=True)
        fd, tmp = tempfile.mkstemp(dir=data_dir, prefix=".jwt_secret.", suffix=".tmp")
        try:
            with os.fdopen(fd, "w", encoding="utf-8") as f:
                f.write(new_secret)
            os.replace(tmp, secret_path)
            _chmod_600(str(secret_path))
        except Exception:
            try:
                os.unlink(tmp)
            except OSError:
                pass
            raise
    except OSError:
        _log.warning(
            "Cannot persist JWT secret to %s (read-only?); using an in-memory "
            "random secret. All logins will be invalidated on restart — set "
            "PT_JWT_SECRET in production.",
            secret_path,
        )
        return new_secret
    _log.info("Generated and persisted a new JWT secret: %s", secret_path)
    return new_secret


def _resolve_onetap_mode() -> bool:
    """集成/独立模式显式二选一：只有 PT_ONETAP_INTEGRATION=1 才进集成模式。

    拼错的值直接启动失败，而不是悄悄退回独立模式——模式混用只能靠报错暴露。
    """
    raw = os.environ.get("PT_ONETAP_INTEGRATION", "")
    if raw in ("", "0"):
        return False
    if raw == "1":
        return True
    raise RuntimeError(
        "PT_ONETAP_INTEGRATION 只接受 0 或 1（当前值 %r）：模式必须显式选择" % raw
    )


class Settings:
    def __init__(self) -> None:
        self.data_dir: str = os.environ.get("PT_DATA_DIR") or _default_data_dir()
        self.db_path: str = str(Path(self.data_dir) / "phitogether.db")
        self.charts_dir: str = str(Path(self.data_dir) / "charts")
        # Shared chart library written by tools/fetch_phigros_charts.py: one
        # audio/cover per song plus one JSON per difficulty, packed into .pez
        # downloads on demand. See server/README.md.
        self.charts_lib_dir: str = str(Path(self.data_dir) / "charts-lib")
        # Chapter membership reference data (generated by tools/build_chapters.py)
        self.chapters_file: str = str(server_root() / "tools" / "phigros_chapters.json")
        self.onetap_integration: bool = _resolve_onetap_mode()
        self.onetap_service_key: str = os.environ.get("PT_ONETAP_SERVICE_KEY", "")
        self.onetap_db_path: str = os.environ.get("PT_ONETAP_DB") or str(
            Path(self.data_dir) / "phitogether-onetap.db"
        )
        if self.onetap_integration:
            # 服务密钥是集成模式唯一的准入凭据：缺失或太短（<32）时启动直接失败，
            # 绝不带着弱密钥跑起来。
            if len(self.onetap_service_key) < 32:
                raise RuntimeError(
                    "PT_ONETAP_SERVICE_KEY 缺失或不足 32 字符：集成模式拒绝启动"
                )
            # 集成模式没有 JWT：身份由网关注入，因此这里不生成/读取签名密钥。
            self.jwt_secret = ""
        else:
            self.jwt_secret = _resolve_jwt_secret(self.data_dir)
        self.jwt_access_expire_minutes: int = 15
        self.jwt_refresh_expire_days: int = 7
        self.static_dir: str = os.environ.get("PT_STATIC_DIR") or str(
            server_root().parent / "dist"
        )
        self.host: str = os.environ.get("PT_HOST", "127.0.0.1")
        self.port: int = int(os.environ.get("PT_PORT", "8000"))


_settings_singleton: Settings | None = None


def get_settings() -> Settings:
    global _settings_singleton
    if _settings_singleton is None:
        _settings_singleton = Settings()
    return _settings_singleton
